services:
  - type: web
    runtime: static
    name: fowler-optical-testing
    buildCommand: ./build-static.sh
    staticPublishPath: ./dist
    buildFilter:
      paths:
        - data/**
        - static/**
        - templates/**
        - build.py
        - build-static.sh
        - requirements.txt
